Fix loop condition
`name` field in `struct opcode_struct` is an array,
so the condition is always false.

```sh
$ gcc -o m68kmake -I. -Wall -Werror -DM68K_COMPILE_FOR_MAME=0 m68kmake.c
m68kmake.c:652:36: error: comparison of array 'op->name' not equal to a null pointer is always true [-Werror,-Wtautological-pointer-compare]
        for(op = g_opcode_input_table;op->name != NULL;op++)
                                      ~~~~^~~~    ~~~~
m68kmake.c:668:36: error: comparison of array 'op->name' not equal to a null pointer is always true [-Werror,-Wtautological-pointer-compare]
        for(op = g_opcode_input_table;op->name != NULL;op++)
                                      ~~~~^~~~    ~~~~
2 errors generated.
```